# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-08 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25, null=True)),
                ('first_name', models.CharField(db_column='first_name', max_length=50)),
                ('last_name', models.CharField(db_column='last_name', max_length=50)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('executive', models.IntegerField(blank=True, null=True)),
                ('executive_assistant', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=25, null=True)),
                ('email', models.EmailField(max_length=50, null=True, unique=True)),
                ('supports', models.CharField(blank=True, max_length=100, null=True)),
                ('supported_by', models.CharField(blank=True, db_column='supported_by', max_length=100, null=True)),
                ('space_available', models.CharField(blank=True, db_column='space_available', max_length=255, null=True)),
                ('committee', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('office_location', models.TextField(blank=True, db_column='office_location', max_length=255, null=True)),
                ('admin', models.IntegerField(blank=True, db_column='admin', null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
